### ISSUE TITLE
Security warning when trying to run the script, shuts it down

### ISSUE THREAD

**Issue by AIZeplin** [CyberPunkMetalHead/seo-gpt#2]
I asked ChatGPT about what the message means, and was told it's a security thing about running scripts, and I needed to change execution policies. Sorry man, no way I'm doing that for a random script found on Reddit.... Haven't had this issue with any of the AGI or AutoGPT'ish models out there, so not sure why it should be needed for this.

PS C:\Users\zepli\OneDrive\Skrivebord\SEOGPT\seo-gpt-main> & c:/Users/zepli/OneDrive/Skrivebord/SEOGPT/seo-gpt-main/env/Scripts/Activate.ps1
& : File C:\Users\zepli\OneDrive\Skrivebord\SEOGPT\seo-gpt-main\env\Scripts\Activate.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ & c:/Users/zepli/OneDrive/Skrivebord/SEOGPT/seo-gpt-main/env/Scripts/ ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Users\zepli\OneDrive\Skrivebord\SEOGPT\seo-gpt-main> & c:/Users/zepli/OneDrive/Skrivebord/SEOGPT/seo-gpt-main/env/Scripts/python.exe c:/Users/zepli/OneDrive/Skrivebord/SEOGPT/seo-gpt-main/main.py
Traceback (most recent call last):
  File "c:\Users\zepli\OneDrive\Skrivebord\SEOGPT\seo-gpt-main\main.py", line 6, in <module>
    from utils.logger import *
  File "c:\Users\zepli\OneDrive\Skrivebord\SEOGPT\seo-gpt-main\utils\logger.py", line 4, in <module>
    logging.basicConfig(
  File "C:\Users\zepli\miniconda3\lib\logging\__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "C:\Users\zepli\miniconda3\lib\logging\__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\zepli\miniconda3\lib\logging\__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zepli\\OneDrive\\Skrivebord\\SEOGPT\\seo-gpt-main\\logs\\2023-04-25_log.log'
PS C:\Users\zepli\OneDrive\Skrivebord\SEOGPT\seo-gpt-main>

**Comment by CyberPunkMetalHead** [comment]
You should never run scripts from the Internet without knowing what they do.
